package com.unicauca.maestria.api.msvc_estudiante_docente.common.enums;

public enum TipoPoblacion {

	HABITANTE_CALLE,
	POBLACION_INFANTIL_ICBF,
	MADRES_COMUNITARIAS,
	ARTISTA,AUTOR,COMPOSITOR,
	POBLACION_SISBENIZADA,
	POBLACION_DESMOVILIZADA,
	POBLACION_DESPLAZAMIENTO_FORZADO,
	POBLACION_CENTROS_PSIQUIATRICOS,
	POBLACION_RURAL_MIGRATORIA,
	POBLACION_RURAL_NO_MIGRATORIA,
	POBLACION_CENTROS_CARCELARIOS,
	POBLACION_TERCERA_EDAD,
	ADULTO_MAYOR,
	CABEZA_DE_FAMILIA,
	MUJER_EMBARAZADA,
	MUJER_LACTANTE,
	TRABAJADOR_URBANO,
	TRABAJADOR_RURAL,
	VICTIMA_VIOLENCIA_ARMADA,
	JOVENES_VULNERABLES_RURALES,
	JOVENES_VULNERABLES_URBANOS,
	SIN_OCUPACION,
	NINGUNO
}
